### ISSUE TITLE
Tests appearing when installing this dependency

### ISSUE THREAD

**Issue by ohemelaar** [oarepo/urnparse#1]
When installing this (of a package that depends on this) a `tests` folder appears in the `site-packages` folder. It appears to be this projet's tests.

Steps to reproduce:
```
mkvirtualenv -p 3.9 dbg-urnparse
pip install urnparse
cdsitepackages
ls tests
# Shows this projet's tests
```

**Comment by mirekys** [comment]
Hi @ohemelaar, thanks for reporting, this was finally fixed in version 0.2.1 :)
